from FCUtil.block import *

#b = block(2,2,1/3.0,top_thickness=-0.02,unit=1.6*2))
#b = block(2,2,1/3.0,has_ridges=False) # block4
#b = block(2,2,1/3.0,has_ridges=False,has_under_tube_cavities=False) # block5
#b = block(2,2,1/3.0,has_ridges=False,has_under_tubes=False,has_knobs=False) # block6
#b = block(2,2,1/3.0,wall_thickness=1.4,has_ridges=False,has_under_tubes=False,has_knobs=False) # block7
#b = block(2,2,1/3.0,wall_thickness=1.45,has_ridges=False,has_under_tubes=False,has_knobs=False) # block8
#b = block(2,2,1,wall_thickness=1.45,has_ridges=False,under_tube_outer_diameter=(5*sqrt(2)-3)*(1.6)+0.05,
#          bottom_play=0.1) # block9
#b = block(2,8,1/3.0,wall_thickness=1.45,has_ridges=False,under_tube_outer_diameter=(5*sqrt(2)-3)*(1.6)+0.05,
#          bottom_play=0.1) # block10

#b = tube(2,2,1,has_under_tube_cavities=False) # tube1
#b = tube(2,2,1,has_under_tube_cavities=False,under_tube_outer_diameter = (5*sqrt(2)-3)*(1.6) - 0.1 +0.05) # tube2
#b = tube(2,2,1,has_under_tube_cavities=True,under_tube_outer_diameter = (5*sqrt(2)-3)*(1.6) - 0.1 +0.05) # tube3
#b = tube(2,2,1,has_under_tube_cavities=False,under_tube_outer_diameter = (5*sqrt(2)-3)*(1.6)) # tube4
#b = tube(2,2,1,has_under_tube_cavities=True,under_tube_outer_diameter = (5*sqrt(2)-3)*(1.6)) # tube5
#b = tube(2,2,1,has_under_tube_cavities=False,under_tube_outer_diameter = (5*sqrt(2)-3)*(1.6)+0.05) # tube6
#b = tube(2,2,1,has_under_tube_cavities=True,under_tube_outer_diameter = (5*sqrt(2)-3)*(1.6)+0.05) # tube7
#b = tube(2,2,1,has_under_tube_cavities=False,under_tube_outer_diameter = (5*sqrt(2)-3)*(1.6)+0.10) # tube8
#b = tube(2,2,1,has_under_tube_cavities=True,under_tube_outer_diameter = (5*sqrt(2)-3)*(1.6)+0.10) # tube9
#b = block(2,2,1,has_ridges=False,under_tube_outer_diameter=(5*sqrt(2)-3)*(1.6)+0.1,
#          bottom_play=0.1,knob_diameter=3.0*1.6 + 0.20) # block11
#b = block(2,2,1/3.0,has_ridges=False,under_tube_outer_diameter=(5*sqrt(2)-3)*(1.6)+0.1,
#          bottom_play=0.1,knob_diameter=3.0*1.6 + 0.15) # block12
#b = block(2,2,1,has_ridges=False,under_tube_outer_diameter=(5*sqrt(2)-3)*(1.6)+0.1,
#          bottom_play=0.1,knob_diameter=3.0*1.6 + 0.15) # block13
#b = block(2,6,1/3.0,has_ridges=False,under_tube_outer_diameter=(5*sqrt(2)-3)*(1.6)+0.1,
#          bottom_play=0.1,knob_diameter=3.0*1.6 + 0.15,has_vertical_holes=1) # block14
#b = block(2,4,1,has_ridges=False,under_tube_outer_diameter=(5*sqrt(2)-3)*(1.6)+0.1,
#          bottom_play=0.1,knob_diameter=3.0*1.6 + 0.15) # block15
#b = block(2,6,1/3.0,has_ridges=False,under_tube_outer_diameter=(5*sqrt(2)-3)*(1.6)+0.1,
#          bottom_play=0.1,knob_diameter=3.0*1.6 + 0.15) # block16
#b = block(1,2,1.0,has_ridges=False,has_under_tubes=False, knob_diameter=3.0*1.6 + 0.15,
#          bottom_play=0.1, has_horizontal_holes=True) # block17
#b = block(1,2,1.0,has_ridges=False,has_under_tubes=False, knob_diameter=3.0*1.6 + 0.15,
#          bottom_play=0.1, has_horizontal_holes=True, horizontal_hole_diameter=3.0 * 1.6 + 0.05 * mm, has_knobs=False) # block18
#b = block(1,2,1.0,has_ridges=False,has_under_tubes=False, knob_diameter=3.0*1.6 + 0.15,
#          bottom_play=0.1, has_horizontal_holes=True, horizontal_hole_diameter=3.0 * 1.6) # block19

if False:
  b = box_corner()
  show(b)
   
  b2 = box_corner()
  b2.rotate(Base.Vector(0,0,0), Base.Vector(0,0,1), -180)
  b2.translate((-0.3, 2*5*1.6, 0))
  show(b2)
   
  bridge = makeBox(2.0, 2*5*1.6-2*.1, 0.150)
  bridge.translate((-1.0, 0.1, 0))
  show(bridge)

# box_side_bottom_with_support
if True:
  hunit = 5*1.6
  vunit = 6*1.6
  slot_depth = 0.7*vunit
  b = box_side_bottom(12)
  top_b, bottom_b = vsplit(b, -2.5)
  bridge = makeBox(2.2+.1+slot_depth, 12*hunit, 0.150)
  bridge.translate((-2.2, 0, 0))
  support = makeBox(1.2, 12*hunit, vunit-.1)
  support.translate((-2.2,0,-vunit+.1))
  support = support.fuse(bridge)
  top_b = top_b.fuse(support)
  show(top_b)
  show(bottom_b)
  #show(support)

if False:
  b = box_side_bottom(12)
  show(b)

if False:
  b = myblock(2,6,1,has_struts=1,strut_sides=1)
  show(b)
  